using System;
using System.Collections.Generic;

namespace Int.Victoria.Scheduler.Models
{
    public partial class Corecustomermayora
    {
        public string? GeUnitHolderIdno { get; set; }
        public string? GeExternalUnitHolder { get; set; }
        public string? GeReferenceNo { get; set; }
        public string? GeCustomerType { get; set; }
        public DateTime? GeBirthDate { get; set; }
        public string? GeIdnationality { get; set; }
        public string? GeNpwp { get; set; }
        public string? GeMotherName { get; set; }
        public string? GeIdtype { get; set; }
        public string? GeIdnumber { get; set; }
        public DateTime? GeIdissueDate { get; set; }
        public DateTime? GeIdexpired { get; set; }
        public string? Beneficiaries { get; set; }
        public string? OcIdoccupation { get; set; }
        public string? GeIdsponsorship { get; set; }
        public double? GeMinUnitHold { get; set; }
        public long? GeMinTimePeriod { get; set; }
        public string? GeIddividendInvest { get; set; }
        public string? GeIdstatus { get; set; }
        public string? GeRemark { get; set; }
        public string? GeNpwpissuedDate { get; set; }
        public string? GeFirstName { get; set; }
        public string? GeMiddleName { get; set; }
        public string? GeLastName { get; set; }
        public string? GeBirthPlace { get; set; }
        public string? GeIdeducation { get; set; }
        public string? GeSourceOfFund { get; set; }
        public string? Idobjectives { get; set; }
        public string? OcIdincome { get; set; }
        public string? GeIdcharacteristic { get; set; }
        public string? GeIdmaritalStatus { get; set; }
        public string? GeIdcompanyType { get; set; }
        public string? GeIdsex { get; set; }
        public string? GeIdreligi { get; set; }
        public string? GeIddomisili { get; set; }
        public bool? GeIsAria { get; set; }
        public DateTime? IiSkdexpired { get; set; }
        public string? IiSkd { get; set; }
        public string? PosSpouseName { get; set; }
        public DateTime? GeCompanyEstablishedDate { get; set; }
        public string? GeNickName { get; set; }
        public string? GeSurname { get; set; }
        public string? GeIdreligiOtherText { get; set; }
        public string? GeNumberofDependentsOthers { get; set; }
        public string? GeIdeducationOtherText { get; set; }
        public string? GeIdtitleBeforeName { get; set; }
        public string? GeIdtitleBeforeNameOtherText { get; set; }
        public string? GeIdtitleAfterName { get; set; }
        public string? GeIdtitleAfterNameOtherText { get; set; }
        public string? GePassport { get; set; }
        public DateTime? GePassportRegistrationDate { get; set; }
        public DateTime? GePassportExpiryDate { get; set; }
        public string? GeKimsorKitas { get; set; }
        public DateTime? GeKimsorKitasregistrationDate { get; set; }
        public DateTime? GeKimsorKitasexpiryDate { get; set; }
        public string? GeKitap { get; set; }
        public DateTime? GeKitapregistrationDate { get; set; }
        public DateTime? GeKitapexpiryDate { get; set; }
        public string? GePlaceofEstablishment { get; set; }
        public string? GeLineofBusiness { get; set; }
        public string? GeTypeofBusinessOthers { get; set; }
        public string? GeCharacteristicOthers { get; set; }
        public string? GeLocalOwnershipPercentage { get; set; }
        public string? GeForeignOwnershipPercentage { get; set; }
        public string? IiNoTdp { get; set; }
        public DateTime? IiTdpissuedAt { get; set; }
        public DateTime? IiTdpexpiryDate { get; set; }
        public string? IiSiup { get; set; }
        public DateTime? IiSiupissuedAt { get; set; }
        public DateTime? IiSiupexpiryDate { get; set; }
        public DateTime? IiSkdissuedAt { get; set; }
        public string? IiNoIjinPma { get; set; }
        public DateTime? IiNoIjinPmaexpiryDate { get; set; }
        public DateTime? IiNoIjinPmaissuedAt { get; set; }
        public string? IiNoIjinUsahaLain { get; set; }
        public DateTime? IiNoIjinUsahaLainDate { get; set; }
        public string? IiDeedofEstablishment { get; set; }
        public DateTime? IiDeedofEstablishmentDate { get; set; }
        public string? IiNotaryName { get; set; }
        public DateTime? IiNotaryAt { get; set; }
        public string? IiLastAmendementofArticleofAssociationNo { get; set; }
        public DateTime? IiLastAmendementofArticleofAssociationDate { get; set; }
        public string? IiNotaryName2 { get; set; }
        public DateTime? IiNotaryAt2 { get; set; }
        public string? OcIdoccupationOther { get; set; }
        public string? Description { get; set; }
        public string? OcDivision { get; set; }
        public string? OcLengthOfEmployment { get; set; }
        public string? OcOccupationLineOfBusiness { get; set; }
        public string? OcCompanyTotalAsset { get; set; }
        public string? OcTotalSales { get; set; }
        public string? OcNetProfit { get; set; }
        public string? OcNumberOfEmployees { get; set; }
        public string? OcIdincomeAdditional { get; set; }
        public string? OcIdsourceOfMainIncome { get; set; }
        public string? OcIdsourceOfMainIncomeOther { get; set; }
        public string? OcIdsourceAdditionalIncome { get; set; }
        public string? OcIdsourceAdditionalIncomeOther { get; set; }
        public string? OcTotalIncome { get; set; }
        public string? OcIdexpensePerMonth { get; set; }
        public string? PosFatherName { get; set; }
        public string? PosMotherName2 { get; set; }
        public string? PosSpouseBirthPlace { get; set; }
        public DateTime? PosSpouseBirthDate { get; set; }
        public string? PosIdspouseOccupation { get; set; }
        public string? PosIdspouseOccupationOther { get; set; }
        public string? PosSpousePosition { get; set; }
        public string? PosSpouseDivisi { get; set; }
        public string? PosSpouseLengthOfEmployment { get; set; }
        public string? PosSpouseLineOfBusiness { get; set; }
        public string? PosSpouseCompanyTotalAsset { get; set; }
        public string? PosSpouseTotalAsset { get; set; }
        public string? PosSpouseNetProfit { get; set; }
        public string? PosSpouseNumberOfEmployees { get; set; }
        public string? PosIdspouseIncome { get; set; }
        public string? PosIdspouseIncomeAdditional { get; set; }
        public string? PosIdspouseSourceAdditionalIncome { get; set; }
        public string? PosIdspouseSourceAdditionalIncomeOther { get; set; }
        public string? PosIdspouseSourceOfMainIncome { get; set; }
        public string? PosIdspouseSourceOfMainIncomeOther { get; set; }
        public string? PosSpouseTotalIncome { get; set; }
        public string? PosIdspouseExpenseMonth { get; set; }
        public string? GeSid { get; set; }
        public string? GeFullName { get; set; }
        public string? GeFundUnitAccount { get; set; }
    }
}
