using System;
using System.Collections.Generic;

namespace Int.Victoria.Scheduler.Models
{
    public partial class TcustomerHistory
    {
        public long? Idcustomer { get; set; }
        public string? UnitHolderIdno { get; set; }
        public string? CodeBroker { get; set; }
        public string? Cifno { get; set; }
        public string? ExternalUnitHolder { get; set; }
        public string? ReferenceNo { get; set; }
        public string? InvestorType { get; set; }
        public string? FullName { get; set; }
        public string? Sex { get; set; }
        public string? Idmarital { get; set; }
        public DateTime? BirthDate { get; set; }
        public string? Idnationality { get; set; }
        public string? Npwp { get; set; }
        public string? MotherName { get; set; }
        public string? Idtype { get; set; }
        public string? Idnumber { get; set; }
        public DateTime? Idissue { get; set; }
        public DateTime? Idexpired { get; set; }
        public string? Beneficiaries { get; set; }
        public string? Idoccupation { get; set; }
        public string? HomeAddress { get; set; }
        public string? HomeCity { get; set; }
        public string? HomeCountry { get; set; }
        public string? HomeZip { get; set; }
        public string? MailAddress { get; set; }
        public string? MailCity { get; set; }
        public string? MailCountry { get; set; }
        public string? MailZip { get; set; }
        public string? HomePhone { get; set; }
        public string? OfficePhone { get; set; }
        public string? Fax { get; set; }
        public string? Email { get; set; }
        public string? Idsponsorship { get; set; }
        public double? MinUnitHold { get; set; }
        public int? MinTimePeriod { get; set; }
        public string? IddividendInvest { get; set; }
        public bool? DocId { get; set; }
        public bool? DocNpwp { get; set; }
        public bool? DocAkta { get; set; }
        public bool? DocNotary { get; set; }
        public bool? DocAttorney { get; set; }
        public string? IdbankCustody { get; set; }
        public DateTime? OpDate { get; set; }
        public DateTime? EntryDate { get; set; }
        public string? EntryUser { get; set; }
        public DateTime? EditDate { get; set; }
        public string? EditUser { get; set; }
        public DateTime? ApprovedDate { get; set; }
        public string? ApprovedUser { get; set; }
        public DateTime? CloseDate { get; set; }
        public string? CloseUser { get; set; }
        public string? Source { get; set; }
        public DateTime? SourceDate { get; set; }
        public string? SourceBank { get; set; }
        public string? Idstatus { get; set; }
        public string? CodeDrawer { get; set; }
        public string? Remark { get; set; }
        public string? CompanyType { get; set; }
        public DateTime? EstablishDate { get; set; }
        public string? AuthPersonName { get; set; }
        public string? AuthPersonPhone { get; set; }
        public string? ContPersonName { get; set; }
        public string? ContPersonPhone { get; set; }
        public string? MobilePhone { get; set; }
        public DateTime? NpwpissuedDate { get; set; }
        public string? ClientGroup { get; set; }
        public int? ProfileId { get; set; }
        public int? ProfileScore { get; set; }
        public string? LogUser { get; set; }
        public DateTime? LogDate { get; set; }
        public string? LastName1 { get; set; }
        public string? BirthPlace1 { get; set; }
        public int? IdeducationGroup { get; set; }
        public int? Ideducation1 { get; set; }
        public string? IdsourceOfFundsGroup { get; set; }
        public int? IdsourceOfFunds1 { get; set; }
        public string? IdaimsAndObjectivesGroup { get; set; }
        public int? IdaimsAndObjectives1 { get; set; }
        public string? IdincomeGroup { get; set; }
        public int? Idincome1 { get; set; }
        public string? Idcity11 { get; set; }
        public string? Idcity21 { get; set; }
        public string? IdcharacteristicGroup { get; set; }
        public int? Idcharacteristic1 { get; set; }
        public string? Skd1 { get; set; }
        public string? MiddleName { get; set; }
        public string? LastName { get; set; }
        public string? BirthPlace { get; set; }
        public int? Ideducation { get; set; }
        public int? IdsourceOfFunds { get; set; }
        public int? IdaimsAndObjectives { get; set; }
        public int? Idincome { get; set; }
        public string? Idcity1 { get; set; }
        public string? Idcity2 { get; set; }
        public int? Idcharacteristic { get; set; }
        public string? IdmaritalStatusGroup { get; set; }
        public int? IdmaritalStatus { get; set; }
        public string? IdnationalityAriaGroup { get; set; }
        public int? IdnationalityAria { get; set; }
        public string? IdoccupationAriaGroup { get; set; }
        public int? IdoccupationAria { get; set; }
        public string? IdtypeIdentityGroup { get; set; }
        public int? IdtypeIdentity { get; set; }
        public string? IdcompanyTypeGroup { get; set; }
        public int? IdcompanyType { get; set; }
        public string? IdsexGroup { get; set; }
        public int? Idsex { get; set; }
        public string? IdreligiGroup { get; set; }
        public int? Idreligi { get; set; }
        public string? IddomisiliGroup { get; set; }
        public int? Iddomisili { get; set; }
        public bool? IsAria { get; set; }
        public string? Skd { get; set; }
    }
}
