using System;
using System.Collections.Generic;

namespace Int.Victoria.Scheduler.Models
{
    public partial class TgenuitempTincome
    {
        public long TgenuitempTableId { get; set; }
        public string TgenuitempSessionId { get; set; } = null!;
        public long? TgenuitempIdmaster { get; set; }
        public long? TgenuitempIddetail { get; set; }
        public short TgenuitempChangeFlag { get; set; }
        public string TgenuitempSysCreatedBy { get; set; } = null!;
        public DateTime TgenuitempSysCreatedTime { get; set; }
        public string TgenuitempSysCreatedHost { get; set; } = null!;
        public string? TgenuitempSysModifiedBy { get; set; }
        public DateTime? TgenuitempSysModifiedTime { get; set; }
        public string? TgenuitempSysModifiedHost { get; set; }
        public long? Idincome { get; set; }
        public long? Idcustomer { get; set; }
        public double? KasMasuk1 { get; set; }
        public double? KasMasuk2 { get; set; }
        public double? KasMasuk3 { get; set; }
        public double? Bonus1 { get; set; }
        public double? Bonus2 { get; set; }
        public double? Bonus3 { get; set; }
        public double? DevidenSaham1 { get; set; }
        public double? DevidenSaham2 { get; set; }
        public double? DevidenSaham3 { get; set; }
        public double? IncomeBunga1 { get; set; }
        public double? IncomeBunga2 { get; set; }
        public double? IncomeBunga3 { get; set; }
        public double? IncomeSewa1 { get; set; }
        public double? IncomeSewa2 { get; set; }
        public double? IncomeSewa3 { get; set; }
        public double? PenerimaanLain1 { get; set; }
        public double? PenerimaanLain2 { get; set; }
        public double? PenerimaanLain3 { get; set; }
        public double? TotalIncome1 { get; set; }
        public double? TotalIncome2 { get; set; }
        public double? TotalIncome3 { get; set; }
        public double? RumahTangga1 { get; set; }
        public double? RumahTangga2 { get; set; }
        public double? RumahTangga3 { get; set; }
        public double? PendidikanAnak1 { get; set; }
        public double? PendidikanAnak2 { get; set; }
        public double? PendidikanAnak3 { get; set; }
        public double? Transportasi1 { get; set; }
        public double? Transportasi2 { get; set; }
        public double? Transportasi3 { get; set; }
        public double? Utilitas1 { get; set; }
        public double? Utilitas2 { get; set; }
        public double? Utilitas3 { get; set; }
        public double? Hobby1 { get; set; }
        public double? Hobby2 { get; set; }
        public double? Hobby3 { get; set; }
        public double? Sewa1 { get; set; }
        public double? Sewa2 { get; set; }
        public double? Sewa3 { get; set; }
        public double? TunjanganOrangTua1 { get; set; }
        public double? TunjanganOrangTua2 { get; set; }
        public double? TunjanganOrangTua3 { get; set; }
        public double? PengeluaranPribadi1 { get; set; }
        public double? PengeluaranPribadi2 { get; set; }
        public double? PengeluaranPribadi3 { get; set; }
        public double? Hiburan1 { get; set; }
        public double? Hiburan2 { get; set; }
        public double? Hiburan3 { get; set; }
        public double? Makanan1 { get; set; }
        public double? Makanan2 { get; set; }
        public double? Makanan3 { get; set; }
        public double? Pengobatan1 { get; set; }
        public double? Pengobatan2 { get; set; }
        public double? Pengobatan3 { get; set; }
        public double? PengeluaranTetapLain1 { get; set; }
        public double? PengeluaranTetapLain2 { get; set; }
        public double? PengeluaranTetapLain3 { get; set; }
        public double? TotalPengeluaranRutin1 { get; set; }
        public double? TotalPengeluaranRutin2 { get; set; }
        public double? TotalPengeluaranRutin3 { get; set; }
        public double? TabunganPendidikan1 { get; set; }
        public double? TabunganPendidikan2 { get; set; }
        public double? TabunganPendidikan3 { get; set; }
        public double? TabunganHariTua1 { get; set; }
        public double? TabunganHariTua2 { get; set; }
        public double? TabunganHariTua3 { get; set; }
        public double? InvestasiLain1 { get; set; }
        public double? InvestasiLain2 { get; set; }
        public double? InvestasiLain3 { get; set; }
        public double? PengeluaranMasaDepanLain1 { get; set; }
        public double? PengeluaranMasaDepanLain2 { get; set; }
        public double? PengeluaranMasaDepanLain3 { get; set; }
        public double? TotalPengeluaranMasaDepan1 { get; set; }
        public double? TotalPengeluaranMasaDepan2 { get; set; }
        public double? TotalPengeluaranMasaDepan3 { get; set; }
        public double? KartuKredit1 { get; set; }
        public double? KartuKredit2 { get; set; }
        public double? KartuKredit3 { get; set; }
        public double? CicilanRumah1 { get; set; }
        public double? CicilanRumah2 { get; set; }
        public double? CicilanRumah3 { get; set; }
        public double? CicilanKendaraan1 { get; set; }
        public double? CicilanKendaraan2 { get; set; }
        public double? CicilanKendaraan3 { get; set; }
        public double? CicilanElektronik1 { get; set; }
        public double? CicilanElektronik2 { get; set; }
        public double? CicilanElektronik3 { get; set; }
        public double? PinjamanPribadi1 { get; set; }
        public double? PinjamanPribadi2 { get; set; }
        public double? PinjamanPribadi3 { get; set; }
        public double? CicilanPinjamanLainnya1 { get; set; }
        public double? CicilanPinjamanLainnya2 { get; set; }
        public double? CicilanPinjamanLainnya3 { get; set; }
        public double? TotalCicilan1 { get; set; }
        public double? TotalCicilan2 { get; set; }
        public double? TotalCicilan3 { get; set; }
        public double? Jiwa1 { get; set; }
        public double? Jiwa2 { get; set; }
        public double? Jiwa3 { get; set; }
        public double? Kerugian1 { get; set; }
        public double? Kerugian2 { get; set; }
        public double? Kerugian3 { get; set; }
        public double? AsuransiKendaraan1 { get; set; }
        public double? AsuransiKendaraan2 { get; set; }
        public double? AsuransiKendaraan3 { get; set; }
        public double? AsuransiRumah1 { get; set; }
        public double? AsuransiRumah2 { get; set; }
        public double? AsuransiRumah3 { get; set; }
        public double? AsuransiLainnya1 { get; set; }
        public double? AsuransiLainnya2 { get; set; }
        public double? AsuransiLainnya3 { get; set; }
        public double? TotalPengeluaranAsuransi1 { get; set; }
        public double? TotalPengeluaranAsuransi2 { get; set; }
        public double? TotalPengeluaranAsuransi3 { get; set; }
        public double? Pajak1 { get; set; }
        public double? Pajak2 { get; set; }
        public double? Pajak3 { get; set; }
        public double? TotalPengeluaranPajak1 { get; set; }
        public double? TotalPengeluaranPajak2 { get; set; }
        public double? TotalPengeluaranPajak3 { get; set; }
        public double? TotalExpense1 { get; set; }
        public double? TotalExpense2 { get; set; }
        public double? TotalExpense3 { get; set; }
        public double? Balance1 { get; set; }
        public double? Balance2 { get; set; }
        public double? Balance3 { get; set; }
        public string? SysCreatedBy { get; set; }
        public DateTime? SysCreatedTime { get; set; }
        public string? SysCreatedHost { get; set; }
        public string? SysModifiedBy { get; set; }
        public DateTime? SysModifiedTime { get; set; }
        public string? SysModifiedHost { get; set; }
        public string? SysActionType { get; set; }
        public byte? SysApprovalStatus { get; set; }
        public bool? SysRecStatus { get; set; }
        public string? SysPendingBy { get; set; }
        public DateTime? SysPendingTime { get; set; }
        public string? SysPendingHost { get; set; }
        public string? SysApprovalNotes { get; set; }
        public string? SysApprovedBy { get; set; }
        public DateTime? SysApprovedTime { get; set; }
        public string? SysApprovedHost { get; set; }
        public string? SysDeletedBy { get; set; }
        public DateTime? SysDeletedTime { get; set; }
        public string? SysDeletedHost { get; set; }
    }
}
