name: Continous integration and deployment

on:
  push :
    branches:
      - "main"      
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkoutcode
        uses: actions/checkout@v3
      - name: setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-verision : '5.0.x'
      
      - name: restore dependencies
        run: dotnet restore
      
      - name: Build App
        run: dotnet build -c Release --no-restore
        

  